name: network-policies-app
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

denyByDefault:
  enabled: true
  namespaces:
  - kube-system
  - giantswarm

allowEgressToDNS:
  enabled: false
  namespaces:
  - kube-system
  - giantswarm

allowEgressToProxy:
  enabled: false
  namespaces:
  - kube-system
  - giantswarm
  httpProxy: ""
  httpsProxy: ""
