name: network-policies-app
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

extraPolicies:
  allowGlobalEgressToCoreDNS:
    enabled: false

denyByDefault:
  enabled: true
  namespaces:
  - kube-system
  - giantswarm
