name: network-policies-app
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/network-policies-app
  tag: v0.0.1
  pullPolicy: IfNotPresent
