name: network-policies-app
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

denyByDefault:
  enabled: true
  namespaces:
  - kube-system
  - giantswarm

allowEgressToDNS:
  enabled: false
  namespaces:
  - kube-system
  - giantswarm

allowEgressToProxy:
  enabled: false
  namespaces:
  - kube-system
  - giantswarm
  httpProxy: ""
  httpsProxy: ""

# deprecated: use konnectivityAgent instead
kamaji:
  enabled: false
  namespaces:
  - kube-system

konnectivityAgent:
  enabled: false
  namespaces:
  - kube-system

denyEgressToIMDS:
  enabled: false
  cidrs:
  - 169.254.169.254/32
  # kube-system and giantswarm are always excluded, these are added to them
  excludedNamespaces: []
  excludedNamespaceLabels: []
