{{- if .Values.extraPolicies.allowGlobalEgressToCoreDNS.enabled }}
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-all-pods-in-all-ns-talk-to-coredns
  namespace: kube-system
spec:
  endpointSelector:
    matchLabels: {}
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: coredns
      toPorts:
        - ports:
          - port: "9153"
            protocol: TCP
        - ports:
          - port: "1053"
            protocol: UDP
          - port: "1053"
            protocol: TCP
          - port: "53"
            protocol: UDP
          - port: "53"
            protocol: TCP
          rules:
            dns:
              - matchPattern: "*"
{{- end }}
