version: 2.1
orbs:
  architect: giantswarm/architect@5.13.0

workflows:
  version: 2
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: package and push network-policies-app chart
        app_catalog: cluster-catalog
        app_catalog_test: cluster-test-catalog
        chart: network-policies-app
        filters:
            # Trigger job on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
        push_to_oci_registry: true
